

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."clients" (
    "auth_id" "uuid" NOT NULL,
    "user_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "gender" "text",
    "role" "text",
    "is_active" boolean DEFAULT true,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "plan_id" character varying
);


ALTER TABLE "public"."clients" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."clients_course_progress" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "client_id" "uuid" NOT NULL,
    "module_id" "uuid" NOT NULL,
    "section_id" "uuid" NOT NULL,
    "video_id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."clients_course_progress" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."clients_settings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "client_id" "uuid" NOT NULL,
    "language" "text",
    "notification_live_call" boolean DEFAULT true,
    "notification_learn_reminders" boolean DEFAULT true,
    "notification_feature_updates" boolean DEFAULT true
);


ALTER TABLE "public"."clients_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_modules" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "thumbnail" character varying NOT NULL,
    "display_order" integer NOT NULL
);


ALTER TABLE "public"."course_modules" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_sections" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "module_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "display_order" integer NOT NULL
);


ALTER TABLE "public"."course_sections" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_videos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "section_id" "uuid" NOT NULL,
    "thumbnail" character varying NOT NULL,
    "vimeo_id" character varying,
    "exercise_id" "uuid",
    "display_order" integer
);


ALTER TABLE "public"."course_videos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."exercises_content" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "exercise_id" "uuid" NOT NULL,
    "text" character varying NOT NULL,
    "mp3_url" character varying NOT NULL,
    "translation" character varying NOT NULL,
    "correct_answers" character varying[] NOT NULL,
    "wrong_answers" character varying[] NOT NULL
);


ALTER TABLE "public"."exercises_content" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."exercises_structure" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "lesson_no" smallint NOT NULL,
    "exercise_no" smallint NOT NULL,
    "exercise_type" character varying NOT NULL
);


ALTER TABLE "public"."exercises_structure" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."lessons_structure" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "lesson_no" smallint NOT NULL,
    "num_exercises" smallint NOT NULL,
    "letter" "text" NOT NULL
);


ALTER TABLE "public"."lessons_structure" OWNER TO "postgres";


ALTER TABLE "public"."course_modules" ALTER COLUMN "display_order" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."modules_display_order_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."plans" (
    "id" character varying NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "price" numeric,
    "duration_days" bigint,
    "features" "json"
);


ALTER TABLE "public"."plans" OWNER TO "postgres";


COMMENT ON TABLE "public"."plans" IS 'All sort of plans for qsk-methode';



CREATE TABLE IF NOT EXISTS "public"."submitted_exercises" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "client_id" "uuid" NOT NULL,
    "lesson_no" smallint NOT NULL,
    "exercise_id" "uuid" NOT NULL,
    "exercise_no" smallint NOT NULL,
    "time_ms" bigint NOT NULL,
    "points" numeric DEFAULT '0'::numeric NOT NULL,
    "num_correct_answers" smallint,
    "lesson_progress" numeric,
    "has_passed_exercise" boolean DEFAULT false NOT NULL,
    "has_passed_lesson" boolean DEFAULT false NOT NULL,
    "earned_hasanat" integer DEFAULT 0 NOT NULL,
    "submitted_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL
);


ALTER TABLE "public"."submitted_exercises" OWNER TO "postgres";


COMMENT ON TABLE "public"."submitted_exercises" IS 'Submitted exercises state per client';



ALTER TABLE "public"."course_sections" ALTER COLUMN "display_order" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."video_sections_display_order_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."clients_course_progress"
    ADD CONSTRAINT "clients_course_progress_client_id_key" UNIQUE ("client_id");



ALTER TABLE ONLY "public"."clients_course_progress"
    ADD CONSTRAINT "clients_course_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_pkey" PRIMARY KEY ("auth_id");



ALTER TABLE ONLY "public"."clients_settings"
    ADD CONSTRAINT "clients_settings_client_id_key" UNIQUE ("client_id");



ALTER TABLE ONLY "public"."clients_settings"
    ADD CONSTRAINT "clients_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_videos"
    ADD CONSTRAINT "course_videos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_videos"
    ADD CONSTRAINT "course_videos_section_id_key" UNIQUE ("section_id");



ALTER TABLE ONLY "public"."exercises_content"
    ADD CONSTRAINT "exercises_content_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exercises_structure"
    ADD CONSTRAINT "exercises_lesson_no_key" UNIQUE ("lesson_no");



ALTER TABLE ONLY "public"."exercises_structure"
    ADD CONSTRAINT "exercises_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lessons_structure"
    ADD CONSTRAINT "lessons_lesson_no_key" UNIQUE ("lesson_no");



ALTER TABLE ONLY "public"."lessons_structure"
    ADD CONSTRAINT "lessons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_modules"
    ADD CONSTRAINT "modules_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."plans"
    ADD CONSTRAINT "plans_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."plans"
    ADD CONSTRAINT "plans_title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."submitted_exercises"
    ADD CONSTRAINT "submitted_exercises_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_sections"
    ADD CONSTRAINT "video_sections_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."clients_course_progress"
    ADD CONSTRAINT "clients_course_progress_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("auth_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."clients_course_progress"
    ADD CONSTRAINT "clients_course_progress_module_id_fkey" FOREIGN KEY ("module_id") REFERENCES "public"."course_modules"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."clients_course_progress"
    ADD CONSTRAINT "clients_course_progress_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "public"."course_sections"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."clients_course_progress"
    ADD CONSTRAINT "clients_course_progress_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."course_videos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id");



ALTER TABLE ONLY "public"."clients_settings"
    ADD CONSTRAINT "clients_settings_client_id_fkey1" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("auth_id");



ALTER TABLE ONLY "public"."course_sections"
    ADD CONSTRAINT "course_sections_module_id_fkey" FOREIGN KEY ("module_id") REFERENCES "public"."course_modules"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_videos"
    ADD CONSTRAINT "course_videos_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises_structure"("id");



ALTER TABLE ONLY "public"."course_videos"
    ADD CONSTRAINT "course_videos_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "public"."course_sections"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exercises_content"
    ADD CONSTRAINT "exercises_content_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises_structure"("id");



ALTER TABLE ONLY "public"."exercises_structure"
    ADD CONSTRAINT "exercises_lesson_no_fkey" FOREIGN KEY ("lesson_no") REFERENCES "public"."lessons_structure"("lesson_no");



ALTER TABLE ONLY "public"."submitted_exercises"
    ADD CONSTRAINT "submitted_exercises_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("auth_id");



ALTER TABLE ONLY "public"."submitted_exercises"
    ADD CONSTRAINT "submitted_exercises_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises_structure"("id");



ALTER TABLE ONLY "public"."submitted_exercises"
    ADD CONSTRAINT "submitted_exercises_lesson_no_fkey" FOREIGN KEY ("lesson_no") REFERENCES "public"."lessons_structure"("lesson_no");



ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."clients_course_progress" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."clients_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_modules" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_sections" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_videos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exercises_content" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exercises_structure" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lessons_structure" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."plans" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."submitted_exercises" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON TABLE "public"."clients" TO "anon";
GRANT ALL ON TABLE "public"."clients" TO "authenticated";
GRANT ALL ON TABLE "public"."clients" TO "service_role";



GRANT ALL ON TABLE "public"."clients_course_progress" TO "anon";
GRANT ALL ON TABLE "public"."clients_course_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."clients_course_progress" TO "service_role";



GRANT ALL ON TABLE "public"."clients_settings" TO "anon";
GRANT ALL ON TABLE "public"."clients_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."clients_settings" TO "service_role";



GRANT ALL ON TABLE "public"."course_modules" TO "anon";
GRANT ALL ON TABLE "public"."course_modules" TO "authenticated";
GRANT ALL ON TABLE "public"."course_modules" TO "service_role";



GRANT ALL ON TABLE "public"."course_sections" TO "anon";
GRANT ALL ON TABLE "public"."course_sections" TO "authenticated";
GRANT ALL ON TABLE "public"."course_sections" TO "service_role";



GRANT ALL ON TABLE "public"."course_videos" TO "anon";
GRANT ALL ON TABLE "public"."course_videos" TO "authenticated";
GRANT ALL ON TABLE "public"."course_videos" TO "service_role";



GRANT ALL ON TABLE "public"."exercises_content" TO "anon";
GRANT ALL ON TABLE "public"."exercises_content" TO "authenticated";
GRANT ALL ON TABLE "public"."exercises_content" TO "service_role";



GRANT ALL ON TABLE "public"."exercises_structure" TO "anon";
GRANT ALL ON TABLE "public"."exercises_structure" TO "authenticated";
GRANT ALL ON TABLE "public"."exercises_structure" TO "service_role";



GRANT ALL ON TABLE "public"."lessons_structure" TO "anon";
GRANT ALL ON TABLE "public"."lessons_structure" TO "authenticated";
GRANT ALL ON TABLE "public"."lessons_structure" TO "service_role";



GRANT ALL ON SEQUENCE "public"."modules_display_order_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."modules_display_order_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."modules_display_order_seq" TO "service_role";



GRANT ALL ON TABLE "public"."plans" TO "anon";
GRANT ALL ON TABLE "public"."plans" TO "authenticated";
GRANT ALL ON TABLE "public"."plans" TO "service_role";



GRANT ALL ON TABLE "public"."submitted_exercises" TO "anon";
GRANT ALL ON TABLE "public"."submitted_exercises" TO "authenticated";
GRANT ALL ON TABLE "public"."submitted_exercises" TO "service_role";



GRANT ALL ON SEQUENCE "public"."video_sections_display_order_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."video_sections_display_order_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."video_sections_display_order_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
